services:
  - type: web
    name: csharp-app
    env: dotnet
    region: oregon
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ASM_C#4.dll
    envVars:
      - key: DOTNET_ROOT
        value: /opt/render/.dotnet
      - key: DOTNET_VERSION
        value: 8.0.x  