// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASM_C_4.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251113152202_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartEvent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubImage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PaymentId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Refund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RefundId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatName")
                        .HasColumnType("TEXT");

                    b.HasKey("SeatId");

                    b.HasIndex("SeatGroupId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("SeatGroup", b =>
                {
                    b.Property<int>("SeatGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cols")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PosX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PosY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rotate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeatingChartId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeatGroupId");

                    b.HasIndex("SeatingChartId");

                    b.ToTable("SeatGroups");
                });

            modelBuilder.Entity("SeatingChart", b =>
                {
                    b.Property<int>("SeatingChartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PosX")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PosY")
                        .HasColumnType("INTEGER");

                    b.HasKey("SeatingChartId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("SeatingCharts");
                });

            modelBuilder.Entity("ShowTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("ShowTimes");
                });

            modelBuilder.Entity("ShowTimeSeat", b =>
                {
                    b.Property<int>("ShowTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShowTimeId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("ShowTimeSeats");
                });

            modelBuilder.Entity("ShowTimeTicketGroup", b =>
                {
                    b.Property<int>("ShowTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTicket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TicketSaleEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TicketSaleStart")
                        .HasColumnType("TEXT");

                    b.HasKey("ShowTimeId", "SeatGroupId");

                    b.HasIndex("SeatGroupId");

                    b.ToTable("ShowTimeTicketGroups");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketDetail", b =>
                {
                    b.Property<int>("TicketDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShowTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketDetailId");

                    b.HasIndex("TicketId");

                    b.HasIndex("ShowTimeId", "SeatId")
                        .IsUnique();

                    b.ToTable("TicketDetails");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Payment", b =>
                {
                    b.HasOne("Ticket", "Ticket")
                        .WithOne("Payment")
                        .HasForeignKey("Payment", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Refund", b =>
                {
                    b.HasOne("Ticket", "Ticket")
                        .WithOne("Refund")
                        .HasForeignKey("Refund", "TicketId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.HasOne("SeatGroup", "SeatGroup")
                        .WithMany("Seats")
                        .HasForeignKey("SeatGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SeatGroup");
                });

            modelBuilder.Entity("SeatGroup", b =>
                {
                    b.HasOne("SeatingChart", "SeatingChart")
                        .WithMany("SeatGroups")
                        .HasForeignKey("SeatingChartId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SeatingChart");
                });

            modelBuilder.Entity("SeatingChart", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithOne("SeatingChart")
                        .HasForeignKey("SeatingChart", "EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ShowTime", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("ShowTimes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ShowTimeSeat", b =>
                {
                    b.HasOne("Seat", "Seat")
                        .WithMany("ShowTimeSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowTime", "ShowTime")
                        .WithMany("ShowTimeSeats")
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("ShowTimeTicketGroup", b =>
                {
                    b.HasOne("SeatGroup", "SeatGroup")
                        .WithMany("ShowTimeTicketGroups")
                        .HasForeignKey("SeatGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowTime", "ShowTime")
                        .WithMany("ShowTimeTicketGroups")
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatGroup");

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.HasOne("Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketDetail", b =>
                {
                    b.HasOne("Ticket", "Ticket")
                        .WithMany("TicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShowTimeSeat", "ShowTimeSeat")
                        .WithOne("TicketDetail")
                        .HasForeignKey("TicketDetail", "ShowTimeId", "SeatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ShowTimeSeat");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Navigation("SeatingChart");

                    b.Navigation("ShowTimes");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Seat", b =>
                {
                    b.Navigation("ShowTimeSeats");
                });

            modelBuilder.Entity("SeatGroup", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("ShowTimeTicketGroups");
                });

            modelBuilder.Entity("SeatingChart", b =>
                {
                    b.Navigation("SeatGroups");
                });

            modelBuilder.Entity("ShowTime", b =>
                {
                    b.Navigation("ShowTimeSeats");

                    b.Navigation("ShowTimeTicketGroups");
                });

            modelBuilder.Entity("ShowTimeSeat", b =>
                {
                    b.Navigation("TicketDetail");
                });

            modelBuilder.Entity("Ticket", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Refund");

                    b.Navigation("TicketDetails");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
